/* Registry-driven FXTools editor. Adding an entry requires an AE adapter, not a new UI. */
window.MotionAstraFXToolsUI=(()=>{
'use strict';const $=id=>document.getElementById(id),data=window.MA_FXTOOLS;
let api,current=data.effects[0],target=null,values={},drafts={},busy=false,visible=false,raf=0;
function el(tag,cls,text){const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;}
function defaults(r){const p={};r.parameters.forEach(d=>p[d.id]=d.default);return p;}
function valid(){return Array.from($('ft-parameters').querySelectorAll('input')).every(e=>e.type==='checkbox'||e.checkValidity()&&e.value!=='');}
function sync(){if(!api)return;for(const id of ['ft-apply','ft-update','ft-load','ft-remove'])$(id).disabled=busy||!api.ready()||(['ft-apply','ft-update'].includes(id)&&!valid())||(id==='ft-update'&&!target);$('ft-parameters').querySelectorAll('input').forEach(e=>e.disabled=busy);$('ft-palettes').querySelectorAll('button').forEach(e=>e.disabled=busy);$('ft-back').disabled=busy;}
function stop(){cancelAnimationFrame(raf);raf=0;}
function draw(canvas,r,p,t=0){const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#09090c';c.fillRect(0,0,w,h);c.textAlign='center';c.textBaseline='middle';c.font='800 '+Math.floor(w*.19)+'px Arial';
 if(r.id==='prism'){const a=(p.angle+(p.animate?t*360/p.duration:0))*Math.PI/180,x=w*p.centerX/100,y=h*p.centerY/100,d=w*p.spread/200,g=p.radial?c.createRadialGradient(x,y,0,x,y,d):c.createLinearGradient(x-Math.cos(a)*d,y-Math.sin(a)*d,x+Math.cos(a)*d,y+Math.sin(a)*d);g.addColorStop(0,p.colorA);g.addColorStop(1,p.colorB);c.fillStyle=g;c.shadowColor=p.colorA;c.shadowBlur=p.radius*.15*p.glow;c.filter=p.diffusion?'blur('+p.diffusion*.12+'px)':'none';c.fillText('ASTRA',w/2,h/2);c.filter='none';c.shadowBlur=0;}
 else{c.strokeStyle=p.tint?p.color:'#ffb177';c.lineWidth=3;c.shadowColor=c.strokeStyle;[p.radius*p.spread*.5,p.radius*.5,0].forEach((b,i)=>{c.shadowBlur=b;c.globalAlpha=Math.min(1,p.intensity*(i===0?p.falloff:1));c.strokeRect(w*.2,h*.3,w*.6,h*.4);});c.globalAlpha=1;c.shadowBlur=0;}
 c.fillStyle='#8a8a94';c.font='10px Arial';c.fillText('Illustrative preview',w/2,h-15);
}
function preview(){stop();if(!current||!valid())return;draw($('ft-preview'),current,values);if(!visible||busy||!values.animate||document.body.classList.contains('reduced'))return;const start=performance.now();function tick(now){if(!visible||busy||document.hidden){stop();return;}draw($('ft-preview'),current,values,(now-start)/1000);if(now-start<4000)raf=requestAnimationFrame(tick);}raf=requestAnimationFrame(tick);}
function renderParameters(){const groups={};$('ft-parameters').textContent='';current.parameters.forEach(d=>{if(!groups[d.group]){const g=el('details','ft-group');g.open=true;g.appendChild(el('summary','',d.group));groups[d.group]=g;$('ft-parameters').appendChild(g);}const label=el('label','ft-field',d.label),input=el('input');input.id='ft-param-'+d.id;input.type=d.type;input.required=d.type!=='checkbox';if(d.type==='number'){input.min=d.min;input.max=d.max;input.step=d.step;}if(d.type==='checkbox')input.checked=values[d.id];else input.value=values[d.id];input.oninput=()=>{if(input.checkValidity()&&(input.type==='checkbox'||input.value!=='')){values[d.id]=d.type==='checkbox'?input.checked:d.type==='number'?Number(input.value):input.value;drafts[current.id]=values;preview();}sync();};label.appendChild(input);groups[d.group].appendChild(label);});sync();}
function open(r,p,loaded){if(busy)return;current=r;values=Object.assign({},p||drafts[r.id]||defaults(r));target=loaded?loaded.target:null;$('ft-library').hidden=true;$('ft-editor').hidden=false;$('ft-title').textContent=r.name;$('ft-description').textContent=r.description;$('ft-reference').textContent=r.reference;$('ft-target').textContent=loaded?'Loaded: '+loaded.layerName:'Select visual layers in AE. Apply adds or updates this effect without creating layers.';$('ft-palettes').hidden=r.id!=='prism';renderParameters();$('ft-scroll').scrollTop=0;preview();}
async function load(){const r=await api.action({action:'fxTools',operation:'load',id:current.id});if(r&&r.params)open(current,r.params,r);}
async function apply(update){if(!valid())return;const r=await api.action({action:'fxTools',operation:update?'update':'apply',id:current.id,params:values,target:update?target:null});if(r&&r.changed&&update)load();}
function init(adapter){api=adapter;data.effects.forEach(r=>{const card=el('article','ft-card'),canvas=el('canvas');canvas.width=440;canvas.height=240;draw(canvas,r,defaults(r));const content=el('div','ft-card-content'),custom=el('button','','Customize'),applyButton=el('button','primary','Apply '+r.name);applyButton.dataset.host='';custom.onclick=()=>open(r);applyButton.onclick=()=>api.action({action:'fxTools',operation:'apply',id:r.id,params:drafts[r.id]||defaults(r)});content.append(el('span','eyebrow',r.tag),el('h2','',r.name),el('p','',r.description),custom,applyButton);card.append(canvas,content);$('ft-cards').appendChild(card);});
 [['Violet Ember','#8257ff','#ff934a'],['Ocean Mint','#145bff','#6affbc'],['Rose Gold','#e04486','#ffe29b'],['Polar','#64dfff','#d7c8ff']].forEach(([name,a,b])=>{const button=el('button','',name);button.onclick=()=>{if(busy)return;values.colorA=a;values.colorB=b;drafts[current.id]=values;renderParameters();preview();};$('ft-palettes').appendChild(button);});
 $('ft-back').onclick=()=>{stop();$('ft-editor').hidden=true;$('ft-library').hidden=false;};$('ft-load').onclick=load;$('ft-apply').onclick=()=>apply(false);$('ft-update').onclick=()=>apply(true);$('ft-replay').onclick=preview;$('ft-remove').onclick=async()=>{const r=await api.action({action:'fxTools',operation:'remove',id:current.id,target:target});if(r&&r.changed){target=null;sync();}};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});sync();
}
return {init,setBusy(on){busy=on;if(on)stop();sync();},setVisible(on){visible=on;if(!on)stop();}};
})();
