(() => {
'use strict';
const $=id=>document.getElementById(id),data=window.MA_PRESETS,bridge=window.MotionAstraBridge;
const state={tab:'Text',preset:null,params:{},busy:false,query:'',invalid:new Set()},history=[];
const store={get(k){try{return localStorage.getItem(k);}catch(e){return null;}},set(k,v){try{localStorage.setItem(k,String(v));}catch(e){}}};let timer,pendingRemove=null;
function icon(){if(window.lucide)lucide.createIcons();}
function notice(message,level='info'){clearTimeout(timer);$('notice-text').textContent=message;$('notice-icon').textContent={info:'i',success:'✓',warning:'!',error:'×'}[level]||'i';$('notice').dataset.level=level;$('notice').classList.add('visible');timer=setTimeout(()=>$('notice').classList.remove('visible'),3500);history.unshift({message,level,time:new Date().toLocaleTimeString()});history.splice(30);$('history').textContent='';history.forEach(item=>{const li=document.createElement('li');li.textContent=item.time+' · '+item.level+' · '+item.message;$('history').appendChild(li);});}
function busy(value){state.busy=value;document.querySelectorAll('[data-host]').forEach(b=>b.disabled=value||!bridge.isReady());$('apply').disabled=$('apply').disabled||state.invalid.size>0;$('update').disabled=$('update').disabled||state.invalid.size>0;}
async function refresh(){if(state.busy)return;if(!bridge.isAvailable()){$('status').textContent='Browser preview · install in AE to apply';$('connection').textContent='Preview mode. No After Effects connection.';busy(false);return;}try{const r=await bridge.call({action:'status'});$('status').textContent=r.composition?`${r.composition} · ${r.selected} selected`:'AE connected · open a composition';$('connection').textContent=`After Effects ${r.version} · MotionAstra ${r.hostVersion}`;}catch(e){$('status').textContent=e.message;$('connection').textContent=e.message;}busy(false);}
async function action(payload){if(state.busy)return null;busy(true);try{const r=await bridge.call(JSON.parse(JSON.stringify(payload)));if(r.message)notice(r.message,r.severity||'success');return r;}catch(e){notice(e.message,'error');return null;}finally{busy(false);refresh();}}
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function close(){if(state.busy)return;$('inspector').hidden=true;$('workspace').classList.remove('inspecting');MotionPreview.play($('preview'),false);}
function tab(name){state.tab=name;document.querySelector('#nav .search').hidden=!['Text','Background'].includes(name);close();$('library').hidden=!['Text','Background'].includes(name);$('tools').hidden=name!=='Tools';$('settings').hidden=name!=='Settings';document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',String(b.dataset.tab===name));});if(['Text','Background'].includes(name)){state.query='';$('search').value='';$('library-kicker').textContent=name==='Text'?'TEXT FX':'BACKGROUNDS';$('library-title').textContent=name==='Text'?'Text in motion.':'A little atmosphere.';$('library-help').textContent=name==='Text'?'10 customizable presets · select text or create a new layer.':'Choose a style to generate its own background layer.';render();}document.querySelector('main').scrollTop=0;}
function render(){MotionPreview.clear();$('cards').textContent='';const list=data.presets.filter(p=>p.category===state.tab&&`${p.name} ${p.description}`.toLowerCase().includes(state.query));$('count').textContent=list.length;list.forEach((p,i)=>{const article=el('article','card'),view=el('button','card-preview'),canvas=el('canvas');canvas.width=440;canvas.height=250;view.setAttribute('aria-label','Customize '+p.name);view.append(canvas,el('span','card-number',String(i+1).padStart(2,'0')));view.onclick=()=>open(p);const content=el('div','card-content');content.append(el('span','type',p.category==='Text'?'TEXT ANIMATION':'PROCEDURAL BACKGROUND'),el('h2','',p.name),el('p','',p.description));const actions=el('div','card-actions'),button=el('button','customize','Customize'),apply=el('button','primary card-apply','Apply');button.onclick=()=>open(p);apply.dataset.host='';apply.setAttribute('aria-label','Apply '+p.name);apply.onclick=()=>{const values={};p.parameters.forEach(d=>values[d.id]=d.default);action({action:'apply',id:p.id,params:values});};actions.append(button,apply);content.appendChild(actions);article.append(view,content);$('cards').appendChild(article);MotionPreview.attach(canvas,p);article.onmouseenter=()=>MotionPreview.play(canvas,true);article.onmouseleave=()=>MotionPreview.play(canvas,false);article.onfocusin=()=>MotionPreview.play(canvas,true);article.onfocusout=()=>MotionPreview.play(canvas,false);});if(!list.length)$('cards').appendChild(el('p','empty','No matching effects.'));busy(state.busy);}
function preview(){if(state.preset)MotionPreview.attach($('preview'),state.preset,state.params,true);}
function checkboxValue(value){
 let v=value;for(let i=0;i<4&&v!==null&&typeof v==='object';i++){
  if(Array.isArray(v)&&v.length===1)v=v[0];
  else if(Object.keys(v).length===1&&Object.prototype.hasOwnProperty.call(v,'value'))v=v.value;
  else break;
 }
 if(v===true||v===1)return true;if(v===false||v===0)return false;
 if(typeof v==='string'){const t=v.trim().toLowerCase();if(['true','on','checked'].includes(t))return true;if(['false','off','unchecked'].includes(t))return false;if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/.test(t)){const n=Number(t);if(n===0||n===1)return n===1;}}
 throw Error('Invalid checkbox value');
}
function parameters(){state.invalid.clear();$('parameters').textContent='';const groups={};state.preset.parameters.forEach(d=>{if(!groups[d.group]){const g=el('fieldset','parameter-group');g.appendChild(el('legend','',d.group));$('parameters').appendChild(g);groups[d.group]=g;}const row=el('div','parameter'),label=el('label','',d.label),input=el(d.type==='select'?'select':d.type==='textarea'?'textarea':'input');input.id='param-'+d.id;label.htmlFor=input.id;row.appendChild(label);
const change=v=>{state.params[d.id]=v;state.invalid.delete(d.id);input.removeAttribute('aria-invalid');preview();busy(state.busy);};
if(d.type==='select'){d.options.forEach(o=>{const opt=el('option','',o.label);opt.value=o.value;input.appendChild(opt);});input.value=state.params[d.id];input.onchange=()=>change(Number(input.value));}
else if(d.type==='checkbox'){input.type='checkbox';try{input.checked=checkboxValue(state.params[d.id]);state.params[d.id]=input.checked;}catch(e){input.checked=false;state.invalid.add(d.id);input.setAttribute('aria-invalid','true');notice(d.label+': choose ON or OFF before applying.','warning');}input.onchange=()=>change(input.checked);}
else if(d.type==='range'||d.type==='number'){input.type=d.type;input.min=d.min;input.max=d.id==='duration'?Math.max(d.max,Number(state.params[d.id])):d.max;input.step=d.step;input.value=state.params[d.id];input.className=d.type==='number'?'wide':'';let exact=null;
const commit=(e)=>{const v=Number(e.value);if(e.value===''||!Number.isFinite(v)||v<Number(input.min)||v>Number(input.max)||(d.step===1&&!Number.isInteger(v))){state.invalid.add(d.id);e.setAttribute('aria-invalid','true');busy(state.busy);return;}e.removeAttribute('aria-invalid');input.value=v;if(exact)exact.value=v;change(v);};
if(d.type==='range'){exact=el('input','exact');exact.type='number';exact.id='exact-'+d.id;exact.min=input.min;exact.max=input.max;exact.step=d.step;exact.value=input.value;exact.setAttribute('aria-label',d.label+' exact value');exact.oninput=()=>commit(exact);row.appendChild(exact);}input.oninput=()=>commit(input);
}else{if(d.type!=='textarea')input.type=d.type;input.value=state.params[d.id];if(d.maxLength)input.maxLength=d.maxLength;input.className=d.type==='color'?'':'wide';input.oninput=()=>change(input.value);}
row.appendChild(input);groups[d.group].appendChild(row);});busy(state.busy);}
function open(p,values){if(state.busy)return;state.preset=p;state.params={};p.parameters.forEach(d=>state.params[d.id]=values&&values[d.id]!==undefined?values[d.id]:d.default);$('fx-title').textContent=p.name;$('fx-description').textContent=p.description;$('apply').textContent=p.category==='Background'?'Create background':'Apply to selected text';$('update').textContent=p.category==='Background'?'Update / create background':'Update selected FX';$('structural-help').hidden=!p.parameters.some(d=>d.id==='count');$('inspector').hidden=false;$('workspace').classList.add('inspecting');parameters();preview();$('parameter-help').textContent=(p.category==='Background'?'Create always adds a new background. Update edits matching selected backgrounds, or creates one if none match. ':'')+'Animation starts at the layer in-point. Drag [FX End] to retime; Loop is OFF by default. Native sliders update live; Count rebuilds on Update.';document.querySelector('.inspector-scroll').scrollTop=0;$('inspector').scrollTop=0;$('close').focus();}
async function load(){const r=await action({action:'load'});if(r&&r.id){const p=data.presets.concat(data.legacy||[]).find(p=>p.id===r.id);if(p){tab(p.category);open(p,r.params);}}}
function tool(name,extra={}){return action(Object.assign({action:'tool',name},extra));}
$('close').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});$('apply').onclick=()=>{if(state.preset&&!state.invalid.size)action({action:'apply',id:state.preset.id,params:state.params});};$('update').onclick=()=>{if(state.preset&&!state.invalid.size)action({action:'update',id:state.preset.id,params:state.params});};$('load-fx').onclick=load;$('inspector-load').onclick=load;
$('reset').onclick=()=>{if(state.preset)open(state.preset);};$('replay').onclick=preview;$('search').oninput=e=>{state.query=e.target.value.trim().toLowerCase();render();};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(!state.busy)tab(b.dataset.tab);});
const glyphs=['↖','↑','↗','←','·','→','↙','↓','↘'];glyphs.forEach((g,i)=>{const b=el('button','',g);b.dataset.host='';b.setAttribute('aria-label','Anchor '+(i+1));b.onclick=()=>tool('anchor',{x:i%3/2,y:Math.floor(i/3)/2,keep:$('anchor-keep').checked});$('anchor-grid').appendChild(b);});$('quick-anchor').onclick=()=>tool('anchor',{x:.5,y:.5,keep:$('anchor-keep').checked});$('anchor-custom').onclick=()=>tool('anchor',{x:Number($('anchor-x').value)/100,y:Number($('anchor-y').value)/100,keep:$('anchor-keep').checked});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>tool(b.dataset.tool,['newShape','newSolid'].includes(b.dataset.tool)?{color:$('new-layer-color').value}:{}));document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>tool('arrange',{mode:b.dataset.order}));document.querySelectorAll('[data-ease]').forEach(b=>b.onclick=()=>tool('ease',{mode:b.dataset.ease,strength:Number($('ease-strength').value)}));
$('stagger').onclick=()=>tool('stagger',{seconds:Number($('stagger-seconds').value)});$('rename').onclick=()=>tool('rename',{prefix:$('rename-prefix').value});$('offset').onclick=()=>tool('offset',{x:Number($('offset-x').value),y:Number($('offset-y').value),z:Number($('offset-z').value)});$('text-style').onclick=()=>tool('style',{size:Number($('text-size').value),color:$('text-color').value,align:$('text-align').value});
function review(name){pendingRemove=name;$('review').hidden=false;$('review-text').textContent=name==='eraseAll'?'Remove ALL native/third-party Effects stacks and MotionAstra animation from the current selected layers? Other expressions may depend on removed effects. Generated artwork will be removed. Transition layers are disabled; project source comps remain.':'Remove MotionAstra v1/v2 animation, controls and generated artwork from selected layers? Unrelated effects remain. Transition layers are disabled after removal. Other layers and project sources are not deleted.';$('review').scrollIntoView({block:'nearest'});}
$('remove-owned').onclick=()=>review('remove');$('erase-all').onclick=()=>review('eraseAll');$('cancel-remove').onclick=()=>{$('review').hidden=true;pendingRemove=null;};$('confirm-remove').onclick=()=>{if(pendingRemove){const name=pendingRemove;pendingRemove=null;$('review').hidden=true;tool(name);}};
$('show-history').onclick=()=>{tab('Settings');$('history').scrollIntoView({block:'nearest'});};$('refresh').onclick=refresh;$('reduced').checked=store.get('ma2-reduced')==='true';document.body.classList.toggle('reduced',$('reduced').checked);$('reduced').onchange=e=>{store.set('ma2-reduced',e.target.checked);document.body.classList.toggle('reduced',e.target.checked);preview();};
function disclosure(button,target,key,label){const b=$(button),panel=$(target);function set(on){panel.hidden=on;b.setAttribute('aria-expanded',String(!on));b.textContent=label+(on?' ▾':' ▴');}set(store.get(key)==='true');b.onclick=()=>{const on=!panel.hidden;set(on);store.set(key,on);};}
disclosure('fold-nav','nav','ma2-nav','Menu');disclosure('fold-quick','quick','ma252-create','Create');tab('Text');busy(false);refresh();icon();window.addEventListener('focus',refresh);setInterval(()=>{if(!document.hidden&&!state.busy)refresh();},4000);
})();
