const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{create}=require('./host-model.cjs');
const fields=['loop','reverse','manual'];
const cases=[[false,false],[true,true],[0,false],[1,true],['false',false],['true',true],['OFF',false],['on',true],['unchecked',false],['checked',true],[' 0.0 ',false],['1.00',true],['0e0',false],['1e0',true],[[0],false],[[1],true],[{value:false},false],[{value:'off'},false],[{value:'on'},true]];
for(const field of fields)for(const [input,expected] of cases){const e=create();e.comp.add('text').selected=true;const r=e.rpc({action:'apply',id:'counter',params:{[field]:input}});assert.equal(r.changed,1,r.message);const l=e.comp.selectedLayers[0];assert.equal(l.fx.property('MA2 '+field).property(1).value,expected?1:0);const loaded=e.rpc({action:'load'});assert.equal(loaded.params[field],expected);assert.equal(e.rpc({action:'update',id:'counter',params:loaded.params}).changed,1);}
for(const bad of ['', 'maybe',2,-1,[],[0,1],{}, {value:false,other:true}]){const e=create();e.comp.add('text').selected=true;const r=e.rpc({action:'apply',id:'counter',params:{loop:bad}});assert.equal(r.ok,false);assert(r.message.includes('received'));assert(r.message.includes('panel parameter'));assert.equal(e.comp.numLayers,1);}
// Real host values can be boxed; this is deliberately not serialized through JSON first.
for(const [native,expected] of [[new Number(0),false],[new Number(1),true],[new Boolean(false),false],[new String('0.0'),false],[.25,false],[.5,false],[.75,true]]){const e=create();e.comp.add('text').selected=true;e.rpc({action:'apply',id:'counter',params:{}});const l=e.comp.selectedLayers[0];l.fx.property('MA2 loop').property(1).value=native;const r=e.rpc({action:'load'});assert.equal(r.ok,true,r.message);assert.equal(r.params.loop,expected);}
{const e=create();e.comp.add('text').selected=true;e.rpc({action:'apply',id:'counter',params:{}});e.comp.selectedLayers[0].fx.property('MA2 loop').property(1).value='broken';const r=e.rpc({action:'load'});assert.equal(r.ok,false);assert(r.message.includes('AE control'));assert(r.message.includes('broken'));}
// Verify the exact old validation rejection and its corresponding corrected result.
{const e=create();e.comp.add('text').selected=true;const old=path.resolve(__dirname,'../../../v2.5.2/MotionAstra-FX/jsx/hostscript.jsx');if(fs.existsSync(old)){vm.runInContext(fs.readFileSync(old,'utf8'),e.context);assert.equal(e.rpc({action:'apply',id:'counter',params:{loop:'off'}}).ok,false);e.reload();assert.equal(e.rpc({action:'apply',id:'counter',params:{loop:'off'}}).changed,1);}}
console.log('PASS: Loop/Reverse/Manual accepted forms, native boxed/fractional values, OFF preservation, roundtrips, invalid-value no-mutation and diagnostics. Original user value is unknown.');
