const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {create}=require('./host-model.cjs');const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'presets.json')));
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[],env=create();env.comp.add('text').selected=true;env.context.app.fonts={allFonts:[[{postScriptName:'Inter-Regular',familyName:'Inter',styleName:'Regular'}]]};
page.on('pageerror',e=>errors.push(e.message));await page.exposeFunction('hostRpc',p=>env.rpc(p));await page.addInitScript(()=>{const bridge={isAvailable:()=>true,isReady:()=>true,call:async p=>{const r=await window.hostRpc(p);if(!r.ok)throw Error(r.message);if(p.action!=='status')window.lastReply=r;return r;}};Object.defineProperty(window,'MotionAstraBridge',{get:()=>bridge,set(){}});});
await page.goto('file://'+path.join(root,'index.html'));assert.equal(await page.locator('.category-tabs button').allTextContents().then(a=>a.map(s=>s.trim()).join('|')),'Text FX 10|Backgrounds 10|Quick Tools');await page.locator('#fold-quick').click();await page.locator('[data-tab="Tools"]').click();assert(await page.locator('#anchor-grid').isVisible());assert(await page.locator('#search').isHidden());await page.locator('#fold-quick').click();await page.locator('[data-tab="Text"]').click();assert.equal(await page.locator('.card').count(),10);
for(const width of [300,320,380,768,1200]){await page.setViewportSize({width,height:650});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow at '+width);const work=await page.locator('#workspace').boundingBox(),foot=await page.locator('footer').boundingBox();assert(work.y+work.height<=foot.y+1);}
await page.setViewportSize({width:320,height:650});const original=await page.locator('#workspace').boundingBox();await page.locator('#fold-nav').click();await page.locator('#fold-quick').click();const folded=await page.locator('#workspace').boundingBox();assert(folded.height>original.height+50);await page.reload();assert.equal(await page.locator('#fold-nav').getAttribute('aria-expanded'),'false');await page.locator('#fold-nav').click();await page.locator('#fold-quick').click();
await page.locator('#refresh-fonts').click();await page.waitForFunction(()=>document.querySelector('#new-text-font').options.length>1);await page.locator('#new-text-font').selectOption('Inter-Regular');await page.locator('#new-layer-color').fill('#c85e22');for(const kind of ['newShape','newText','newSolid']){const before=env.comp.numLayers;await page.locator('[data-tool="'+kind+'"]').click();await page.waitForFunction(()=>!document.querySelector('[data-tool="newShape"]').disabled);assert.equal(env.comp.numLayers,before+1);assert.equal(env.comp.selectedLayers.length,1);if(kind==='newText')assert.equal(env.comp.selectedLayers[0].text.property('ADBE Text Document').value.font,'Inter-Regular');}for(const r of data.presets){await page.locator(`[data-tab="${r.category}"]`).click();assert.equal(await page.locator('.card').count(),10);await page.fill('#search',r.name);await page.locator('.customize').click();env.comp.items.forEach(l=>l.selected=false);if(r.category==='Text')env.comp.add('text').selected=true;
if(r.category==='Background'){assert.equal(await page.locator('#param-duration').getAttribute('type'),'number');assert.equal(await page.locator('#exact-duration').count(),0);await page.locator('#param-static').check();}assert.equal(await page.locator('#param-loop').count(),0);assert.equal(await page.locator('#param-loopMode option').allTextContents().then(a=>a.join('|')),'Ping-Pong|Cycle|Continue|None');await page.locator('#param-loopMode').selectOption('0');await page.locator('#apply').click();await page.waitForFunction(()=>window.lastReply&&window.lastReply.changed===1);await page.waitForFunction(()=>!document.querySelector('#apply').disabled);assert.equal(env.rpc({action:'load'}).id,r.id);assert.equal(env.rpc({action:'load'}).params.loopMode,0);
await page.locator('#param-manual').check();await page.locator('#exact-progress').fill('40');await page.locator('#update').click();await page.waitForFunction(()=>!document.querySelector('#update').disabled);assert.equal(env.rpc({action:'load'}).params.progress,40);
const applyBox=await page.locator('#apply').boundingBox(),updateBox=await page.locator('#update').boundingBox();assert(Math.abs(applyBox.y-updateBox.y)<1,'Apply and Update must share the bottom row');assert.equal(await page.locator('#inspector-load').count(),0);assert.equal(await page.locator('#quick #load-fx').count(),1);const actions=await page.locator('.inspector-actions').boundingBox(),footer=await page.locator('footer').boundingBox();assert(actions.y+actions.height<=footer.y+1,'Actions overlap status');await page.locator('#close').click();}
// Customized colors survive returning to the card; repeat Generate updates one layer.
await page.locator('[data-tab="Background"]').click();await page.fill('#search','Neon Grid');await page.locator('.customize').click();await page.locator('#param-color2').fill('#ee2244');await page.locator('#close').click();env.comp.items.forEach(l=>l.selected=false);const beforeGenerate=env.comp.numLayers;await page.locator('.card-apply').click();await page.waitForFunction(()=>!document.querySelector('.card-apply').disabled);assert.equal(env.comp.numLayers,beforeGenerate+1);assert.equal(env.rpc({action:'load'}).params.color2,'#ee2244');await page.locator('.card-apply').click();await page.waitForFunction(()=>!document.querySelector('.card-apply').disabled);assert.equal(env.comp.numLayers,beforeGenerate+1);
// Precise counter fields, switcher text and native-control settings roundtrip.
await page.locator('[data-tab="Text"]').click();env.comp.items.forEach(l=>l.selected=false);env.comp.add('text').selected=true;await page.fill('#search','Counter Text');await page.locator('.customize').click();await page.fill('#param-start','-250.5');await page.fill('#param-end','2500.75');await page.locator('#param-decimals').selectOption('2');await page.fill('#param-prefix','Rp ');await page.locator('#apply').click();await page.waitForFunction(()=>!document.querySelector('#apply').disabled);let loaded=env.rpc({action:'load'});assert.equal(loaded.params.start,-250.5);assert.equal(loaded.params.end,2500.75);assert.equal(loaded.params.prefix,'Rp ');
await page.fill('#param-end','');assert(await page.locator('#apply').isDisabled());await page.fill('#param-end','5000');await page.locator('#update').click();await page.waitForFunction(()=>!document.querySelector('#update').disabled);assert.equal(env.rpc({action:'load'}).params.end,5000);
const selected=env.comp.selectedLayers[0];selected.fx.property('MA2 end').property(1).setValue(9999);await page.locator('#load-fx').click();await page.waitForFunction(()=>document.querySelector('#param-end').value==='9999');
await page.setViewportSize({width:320,height:360});await page.locator('#apply').scrollIntoViewIfNeeded();const shortApply=await page.locator('#apply').boundingBox(),shortFooter=await page.locator('footer').boundingBox();assert(shortApply.y+shortApply.height<=shortFooter.y+1,'Apply inaccessible at short height');await page.setViewportSize({width:320,height:650});await page.locator('#fold-nav').click();await page.locator('#fold-quick').click();await page.locator('.inspector-scroll').evaluate(e=>e.scrollTop=190);await page.screenshot({path:path.join(root,'panel-narrow-preview.png')});await page.locator('#fold-nav').click();await page.locator('#fold-quick').click();
await page.locator('#close').click();await page.locator('[data-tab="Tools"]').click();await page.locator('[aria-label="Anchor 1"]').click();await page.waitForFunction(()=>!document.querySelector('#quick-anchor').disabled);assert.deepEqual(Array.from(selected.transform.property('ADBE Anchor Point').value),[0,0]);
await page.locator('#erase-all').click();assert(await page.locator('#review').isVisible());assert(selected.fx.numProperties>0);await page.locator('#cancel-remove').click();assert(selected.fx.numProperties>0);await page.locator('#erase-all').click();await page.locator('#confirm-remove').click();await page.waitForFunction(()=>!document.querySelector('#quick-anchor').disabled);assert.equal(selected.fx.numProperties,0);
assert(await page.locator('#notice').evaluate(e=>e.classList.contains('visible')));await page.waitForTimeout(3700);assert(!await page.locator('#notice').evaluate(e=>e.classList.contains('visible')));await page.locator('#show-history').click();assert(await page.locator('#history li').count()>0);
await page.setViewportSize({width:1200,height:850});await page.locator('[data-tab="Text"]').click();await page.screenshot({path:path.join(root,'panel-preview.png')});await page.locator('[data-tab="Background"]').click();await page.screenshot({path:path.join(root,'background-preview.png')});
await page.locator('[data-tab="Tools"]').click();await page.screenshot({path:path.join(root,'tools-preview.png')});const offline=await browser.newPage();await offline.goto('file://'+path.join(root,'catalog.html'));await offline.locator('[data-tab="Tools"]').click();assert(await offline.locator('#anchor-grid').isVisible());await offline.locator('[data-tab="Text"]').click();await offline.locator('.customize').first().click();assert(await offline.locator('#apply').isDisabled());assert(await offline.locator('#update').isDisabled());assert.deepEqual(errors,[]);await browser.close();console.log('PASS: real Chromium + actual host dispatch/model; all 20 Apply/Update flows, number editing, native settings load, 5 widths, persistent collapse, pinned actions, anchor dispatch, erase confirm/cancel, notification timing/history and offline guard.');})().catch(e=>{console.error(e);process.exit(1);});
