"""Compile the extensible offline FXTools registry and ES3 adapter."""
from pathlib import Path
import json
r=Path(__file__).resolve().parent.parent
data=json.loads((r/'fx-tools.json').read_text());s=json.dumps(data,ensure_ascii=True,separators=(',',':'))
(r/'js/fx-tools-data.js').write_text('window.MA_FXTOOLS='+s+';\n')
(r/'jsx/fx-tools.jsx').write_text('/* Generated by tools/build-fxtools.py */\nvar MotionAstraFXTools=(function(){var registry='+s+';\n'+'\n'.join(f.read_text() for f in sorted((r/'src/fx-tools').glob('*.js')))+'\n'+(r/'src/fx-tools-host.js').read_text()+'\n}());\n')

version=(r/'VERSION').read_text().strip()
target=r/'jsx/fx-tools.jsx'
target.write_text(target.read_text()+'\nMotionAstraFXTools.build='+repr(version)+';\nif(typeof $!=="undefined"&&$.global){$.global.MotionAstraFXTools=MotionAstraFXTools;$.global.MotionAstraModules=$.global.MotionAstraModules||{};$.global.MotionAstraModules.fxTools=MotionAstraFXTools;}\n')
