"""Bundle MIT-licensed YUGraphic text engine with MotionAstra's compact adapter.
Original sources stay byte-for-byte in vendor/yu-text-motion.
"""
from pathlib import Path
import re
r=Path(__file__).resolve().parent.parent
core=(r/'vendor/yu-text-motion/core.js').read_text()
host=(r/'vendor/yu-text-motion/host.js').read_text()
# Settings are embedded into expressions; no redundant native parameter sliders.
host=host.replace('var e=effects(layer).addProperty("ADBE Slider Control");e.name=name;e.property(1).setValue(value);','/* MotionAstra: compact settings are embedded by expression adapter. */')
(r/'jsx/yu-text.jsx').write_text('/* Generated by tools/build-yu.py. YUGraphic MIT license: vendor/yu-text-motion/LICENSE.txt */\nvar MotionAstraYU=(function(){\n'+core+'\n'+host+'\n'+(r/'src/yu-adapter.js').read_text()+'\n}());\n')
